#################################
# Mongo - example configuration #
#################################

# This is an example definition of Mongo service.
# In order to use Mongo, you first must call Mongo::setConfig($pathToYourConfig),
# and then just use the MongoTrait (eg. $this->mongo('Webiny'))
#
# Mongo constructor parameters are: host, database, username, password, collectionPrefix
#
# Collection prefix will be automatically prepended to all queries for you
Mongo:
    Services:
        Webiny:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Host: 127.0.0.1:27017
                Database: webiny
                Username: null
                Password: null
                CollectionPrefix: ''
                Options:
                    w: 1
                    wTimeoutMS: 10000
                    connectTimeoutMS: 60000
                    socketTimeoutMS: 30000
                    fsync: false
                    journal: false
    Driver: \Webiny\Component\Mongo\Driver\Mongo
    ResultClass: \Webiny\Component\Mongo\MongoResult