#################################
# Mongo - example configuration #
#################################

# This is an example definition of Mongo service.
# In order to use Mongo, you first must call Mongo::setConfig($pathToYourConfig),
# and then just use the MongoTrait (eg. $this->mongo('Webiny'))
#
# Mongo constructor parameters are: uri,
#
# Collection prefix will be automatically prepended to all queries for you
Mongo:
    Services:
        Webiny:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Uri: 127.0.0.1:27017
                DriverOptions: []
                CollectionPrefix: ''
            Calls:
                - [selectDatabase, [webiny]]
    Driver: \Webiny\Component\Mongo\Bridge\MongoDb